### ISSUE TITLE
Broken urls

### ISSUE THREAD

**Issue by chenxi116** [facebookresearch/pythia#30] opened 2019-01-30 14:49 UTC
I tried on two of my computers, but the links after `wget` in "README/Quick Start" seem to be broken. Please check.

Also `mkdir data` seems unnecessary in "README/Quick Start".

Also in README, https://www.continuum.io/downloads seems to be an obsolete link to Anaconda.

**Comment by ThegreatShible** [comment] 2019-02-02 13:11
I have the same problem of broken URLs with /data_prep/data_preprocess.md, I think it's the same URLs.
For me it's: 

-  https://s3-us-west-1.amazonaws.com/vqa-suite/val_split/v2_OpenEnded_mscoco_minival2014_questions.json

- https://s3-us-west-1.amazonaws.com/vqa-suite/val_split/v2_OpenEnded_mscoco_val2train2014_questions.json

**Comment by ThegreatShible** [comment] 2019-02-02 18:44
I found the solution for the two link i posted above in the issue #24.
Now I have found other problems with broken links when trying to download pretrained weights for detectron: 

- https://s3-us-west-1.amazonaws.com/pythia-vqa/detectron/FAST_RCNN_MLP_DIM2048_FPN_DIM512.pkl

- https://s3-us-west-1.amazonaws.com/pythia-vqa/detectron/e2e_faster_rcnn_X-101-64x4d-FPN_1x_MLP_2048_FPN_512.yaml

**Comment by KaihuaTang** [comment] 2019-02-03 08:03
> I found the solution for the two link i posted above in the issue #24.
> Now I have found other problems with broken links when trying to download pretrained weights for detectron:
> 
> * https://s3-us-west-1.amazonaws.com/pythia-vqa/detectron/FAST_RCNN_MLP_DIM2048_FPN_DIM512.pkl
> * https://s3-us-west-1.amazonaws.com/pythia-vqa/detectron/e2e_faster_rcnn_X-101-64x4d-FPN_1x_MLP_2048_FPN_512.yaml

I got the same problem

**Comment by yashkant** [comment] 2019-02-05 10:34
Following.

**Comment by abhayk1201** [comment] 2019-02-08 05:02
Following +1

**Comment by endernewton** [comment] 2019-02-19 19:21
Actually we realized that due to internal changes of file services, we **lost the original copies** of the files. :(  Right now we are actively working on reproducing the models based on the features/data remaining on our side, but unfortunately it will 1) take a while, and 2) not be exactly the same for some models. Therefore, we are wondering if anyone who has downloaded the original files could **share it** from your end. Especially we are missing:

1) baseline +VG +VisDal +mirror model
2) ensembled.tar.gz - the ensemble predictions

Please reply to this thread if you or someone around you have a copy on your end. Thanks ahead!

**Comment by meetshah1995** [comment] 2019-02-20 17:11
The bucket links have been changed. Features, metadata files and Detectron models can be downloaded from:

* Data
    * https://dl.fbaipublicfiles.com/pythia/data/answers_vqa.txt
    * https://dl.fbaipublicfiles.com/pythia/data/imdb.tar.gz
    * https://dl.fbaipublicfiles.com/pythia/data/large_vocabulary_vqa.txt
    * https://dl.fbaipublicfiles.com/pythia/data/large_vqa2.0_glove.6B.300d.txt.npy
    * https://dl.fbaipublicfiles.com/pythia/data/v2_OpenEnded_mscoco_minival2014_questions.json
    * https://dl.fbaipublicfiles.com/pythia/data/v2_OpenEnded_mscoco_val2train2014_questions.json
    * https://dl.fbaipublicfiles.com/pythia/data/vocabulary_vqa.txt
    * https://dl.fbaipublicfiles.com/pythia/data/vqa2.0_glove.6B.300d.txt.npy

* Features:
    * https://dl.fbaipublicfiles.com/pythia/features/detectron_fix_100.tar.gz
    * https://dl.fbaipublicfiles.com/pythia/features/rcnn_10_100.tar.gz
    * https://dl.fbaipublicfiles.com/pythia/features/resnet152.tar.gz

* Detectron Model
    * https://dl.fbaipublicfiles.com/pythia/detectron_model/FAST_RCNN_MLP_DIM2048_FPN_DIM512.pkl
    * https://dl.fbaipublicfiles.com/pythia/detectron_model/e2e_faster_rcnn_X-101-64x4d-FPN_1x_MLP_2048_FPN_512.yaml

We're in the process of uploading most of the files and will update the repo shortly with the updated paths.

**Comment by meetshah1995** [comment] 2019-02-21 19:31
All paths except ensembled predictions have been updated and the files are now accessible. Closing this issue for now.

**Closed by meetshah1995** 2019-02-21 19:31 UTC

**Comment by WannaGetDSJobInSanFrancisco** [comment] 2022-02-04 15:00
Met the same issue for Flickr30. I guess this google drive link does not work any more?
- https://drive.google.com/uc?export=download&id=0B_PL6p-5reUAZEM4MmRQQ2VVSlk
```
Traceback (most recent call last):
  File "/<path_to_mmf>/mmf_cli/run.py", line 137, in <module>
    run()
  File "/<path_to_mmf>/mmf_cli/run.py", line 133, in run
    main(configuration, predict=predict)
  File "/<path_to_mmf>/mmf_cli/run.py", line 52, in main
    trainer.load()
  File "/<path_to_mmf>/mmf/trainers/mmf_trainer.py", line 42, in load
    super().load()
  File "/<path_to_mmf>/mmf/trainers/base_trainer.py", line 32, in load
    self.load_datasets()
  File "/<path_to_mmf>/mmf/trainers/mmf_trainer.py", line 79, in load_datasets
    self.dataset_loader = MultiDataModule(self.config)
  File "/<path_to_mmf>/mmf/datasets/multi_datamodule.py", line 33, in __init__
    self.dataset_list, self.config.dataset_config
  File "/<path_to_mmf>/mmf/utils/build.py", line 254, in build_multiple_datamodules
    datamodule_instance.prepare_data(dataset_config)
  File "/<path_to_mmf>/mmf/datasets/base_dataset_builder.py", line 90, in prepare_data
    self.build_dataset(config)
  File "/<path_to_mmf>/mmf/datasets/base_dataset_builder.py", line 145, in build_dataset
    self.build(config, dataset_type, *args, **kwargs)
  File "/<path_to_mmf>/mmf/datasets/mmf_dataset_builder.py", line 74, in build
    self._download_requirement(config, requirement)
  File "/<path_to_mmf>/mmf/datasets/mmf_dataset_builder.py", line 115, in _download_requirement
    resources, download_path, version, "images"
  File "/<path_to_mmf>/mmf/datasets/mmf_dataset_builder.py", line 223, in _download_based_on_attribute
    self._download_resources(resources.get(attribute, []), path, version)
  File "/<path_to_mmf>/mmf/datasets/mmf_dataset_builder.py", line 226, in _download_resources
    download.download_resources(resources, path, version)
  File "/<path_to_mmf>/mmf/utils/download.py", line 397, in download_resources
    download_resource(resource, download_path)
  File "/<path_to_mmf>/mmf/utils/download.py", line 406, in download_resource
    resource.download_file(download_path)
  File "/<path_to_mmf>/mmf/utils/download.py", line 152, in download_file
    redownload=redownload,
  File "/<path_to_mmf>/mmf/utils/download.py", line 475, in download_from_google_drive
    check_header(gd_id, from_google=True)
  File "/<path_to_mmf>/mmf/utils/download.py", line 332, in check_header
    ).format(url)
AssertionError: The url 0B_PL6p-5reUAZEM4MmRQQ2VVSlk is broken. If this is not your own url, please open up an issue on GitHub
```

**Comment by shufangxun** [comment] 2022-03-18 07:04
> * https://drive.google.com/uc?export=download&id=0B_PL6p-5reUAZEM4MmRQQ2VVSlk

have  you solved this problem?

**Comment by RulinShao** [comment] 2022-06-14 22:14
> Met the same issue for Flickr30. I guess this google drive link does not work any more?
> 
>     * https://drive.google.com/uc?export=download&id=0B_PL6p-5reUAZEM4MmRQQ2VVSlk
> 
> 
> ```
> Traceback (most recent call last):
>   File "/<path_to_mmf>/mmf_cli/run.py", line 137, in <module>
>     run()
>   File "/<path_to_mmf>/mmf_cli/run.py", line 133, in run
>     main(configuration, predict=predict)
>   File "/<path_to_mmf>/mmf_cli/run.py", line 52, in main
>     trainer.load()
>   File "/<path_to_mmf>/mmf/trainers/mmf_trainer.py", line 42, in load
>     super().load()
>   File "/<path_to_mmf>/mmf/trainers/base_trainer.py", line 32, in load
>     self.load_datasets()
>   File "/<path_to_mmf>/mmf/trainers/mmf_trainer.py", line 79, in load_datasets
>     self.dataset_loader = MultiDataModule(self.config)
>   File "/<path_to_mmf>/mmf/datasets/multi_datamodule.py", line 33, in __init__
>     self.dataset_list, self.config.dataset_config
>   File "/<path_to_mmf>/mmf/utils/build.py", line 254, in build_multiple_datamodules
>     datamodule_instance.prepare_data(dataset_config)
>   File "/<path_to_mmf>/mmf/datasets/base_dataset_builder.py", line 90, in prepare_data
>     self.build_dataset(config)
>   File "/<path_to_mmf>/mmf/datasets/base_dataset_builder.py", line 145, in build_dataset
>     self.build(config, dataset_type, *args, **kwargs)
>   File "/<path_to_mmf>/mmf/datasets/mmf_dataset_builder.py", line 74, in build
>     self._download_requirement(config, requirement)
>   File "/<path_to_mmf>/mmf/datasets/mmf_dataset_builder.py", line 115, in _download_requirement
>     resources, download_path, version, "images"
>   File "/<path_to_mmf>/mmf/datasets/mmf_dataset_builder.py", line 223, in _download_based_on_attribute
>     self._download_resources(resources.get(attribute, []), path, version)
>   File "/<path_to_mmf>/mmf/datasets/mmf_dataset_builder.py", line 226, in _download_resources
>     download.download_resources(resources, path, version)
>   File "/<path_to_mmf>/mmf/utils/download.py", line 397, in download_resources
>     download_resource(resource, download_path)
>   File "/<path_to_mmf>/mmf/utils/download.py", line 406, in download_resource
>     resource.download_file(download_path)
>   File "/<path_to_mmf>/mmf/utils/download.py", line 152, in download_file
>     redownload=redownload,
>   File "/<path_to_mmf>/mmf/utils/download.py", line 475, in download_from_google_drive
>     check_header(gd_id, from_google=True)
>   File "/<path_to_mmf>/mmf/utils/download.py", line 332, in check_header
>     ).format(url)
> AssertionError: The url 0B_PL6p-5reUAZEM4MmRQQ2VVSlk is broken. If this is not your own url, please open up an issue on GitHub
> ```

Following

**Comment by Wag0nWheels** [comment] 2022-07-22 11:21
> > * https://drive.google.com/uc?export=download&id=0B_PL6p-5reUAZEM4MmRQQ2VVSlk
> 
> have you solved this problem?

have you solved this problem?

**Comment by moon34git** [comment] 2023-05-23 12:36
> > * https://drive.google.com/uc?export=download&id=0B_PL6p-5reUAZEM4MmRQQ2VVSlk
> 
> have you solved this problem?

`# evaluating using a single GPU on 8 datasets
CUDA_VISIBLE_DEVICES=0 python mmf_cli/run.py \
    config=projects/unit/configs/all_8_datasets/shared_dec.yaml \
    datasets=detection_coco,detection_visual_genome,vqa2,visual_entailment,glue_qnli,glue_sst2,glue_mnli_mismatched,glue_qqp \
    model=unit run_type=val training.batch_size=1 \
    checkpoint.resume_zoo=unit.all_8_datasets.shared_dec_with_coco_init`

I found that downloading visual_entailment dataset causes this problem. You can delete it and completely run
