### ISSUE TITLE
I couldn't train the model just show the error ~/pythia/pythia/.vector_cache/wiki.en.bin cannot be opened for loading!

### ISSUE THREAD

**Issue by CYYYYYYYYYYY** [facebookresearch/pythia#77] opened 2019-05-30 04:28 UTC
2019-05-30T12:03:24 INFO: Fetching fastText model for OCR processing
2019-05-30T12:03:24 WARNING: /home/chenying/pythia/pythia/tasks/processors.py:397: UserWarning: No model file present at /home/chenying/pythia/pythia/.vector_cache/wiki.en.bin.
  warnings.warn("No model file present at {}.".format(model_file))

2019-05-30T12:03:24 INFO: Downloading FastText bin
2019-05-30T12:03:24 INFO: Loading fasttext model now from /home/chenying/pythia/pythia/.vector_cache/wiki.en.bin
2019-05-30T12:03:24 ERROR: Traceback (most recent call last):
  File "/home/chenying/anaconda3/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/chenying/anaconda3/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/chenying/pythia/pythia/tasks/multi_task.py", line 73, in __getitem__
    item = self.chosen_task[idx]
  File "/home/chenying/pythia/pythia/tasks/base_task.py", line 155, in __getitem__
    item = self.chosen_dataset[idx]
  File "/home/chenying/anaconda3/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/utils/data/dataset.py", line 81, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/chenying/pythia/pythia/tasks/base_dataset.py", line 49, in __getitem__
    sample = self.get_item(idx)
  File "/home/chenying/pythia/pythia/tasks/vqa/vqa2/dataset.py", line 93, in get_item
    return self.load_item(idx)
  File "/home/chenying/pythia/pythia/tasks/vqa/vizwiz/dataset.py", line 16, in load_item
    sample = super().load_item(idx)
  File "/home/chenying/pythia/pythia/tasks/vqa/vqa2/dataset.py", line 124, in load_item
    current_sample = self.add_ocr_details(sample_info, current_sample)
  File "/home/chenying/pythia/pythia/tasks/vqa/vqa2/dataset.py", line 139, in add_ocr_details
    context = self.context_processor({"tokens": ocr_tokens})
  File "/home/chenying/pythia/pythia/tasks/processors.py", line 155, in __call__
    return self.processor(item)
  File "/home/chenying/pythia/pythia/tasks/processors.py", line 492, in __call__
    self._try_download()
  File "/home/chenying/pythia/pythia/tasks/processors.py", line 407, in _try_download
    self._load_fasttext_model(model_file)
  File "/home/chenying/pythia/pythia/tasks/processors.py", line 466, in _load_fasttext_model
    self.model = load_model(model_file)
  File "/home/chenying/fastText/python/fastText/FastText.py", line 320, in load_model
    return _FastText(path)
  File "/home/chenying/fastText/python/fastText/FastText.py", line 37, in __init__
    self.f.loadModel(model)
ValueError: /home/chenying/pythia/pythia/.vector_cache/wiki.en.bin cannot be opened for loading!

Traceback (most recent call last):
  File "tools/run.py", line 94, in <module>
    run()
  File "tools/run.py", line 83, in run
    trainer.train()
  File "/home/chenying/pythia/pythia/trainers/base_trainer.py", line 217, in train
    for batch in self.train_loader:
  File "/home/chenying/anaconda3/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/home/chenying/anaconda3/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/chenying/anaconda3/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/chenying/anaconda3/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/chenying/pythia/pythia/tasks/multi_task.py", line 73, in __getitem__
    item = self.chosen_task[idx]
  File "/home/chenying/pythia/pythia/tasks/base_task.py", line 155, in __getitem__
    item = self.chosen_dataset[idx]
  File "/home/chenying/anaconda3/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/utils/data/dataset.py", line 81, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/home/chenying/pythia/pythia/tasks/base_dataset.py", line 49, in __getitem__
    sample = self.get_item(idx)
  File "/home/chenying/pythia/pythia/tasks/vqa/vqa2/dataset.py", line 93, in get_item
    return self.load_item(idx)
  File "/home/chenying/pythia/pythia/tasks/vqa/vizwiz/dataset.py", line 16, in load_item
    sample = super().load_item(idx)
  File "/home/chenying/pythia/pythia/tasks/vqa/vqa2/dataset.py", line 124, in load_item
    current_sample = self.add_ocr_details(sample_info, current_sample)
  File "/home/chenying/pythia/pythia/tasks/vqa/vqa2/dataset.py", line 139, in add_ocr_details
    context = self.context_processor({"tokens": ocr_tokens})
  File "/home/chenying/pythia/pythia/tasks/processors.py", line 155, in __call__
    return self.processor(item)
  File "/home/chenying/pythia/pythia/tasks/processors.py", line 492, in __call__
    self._try_download()
  File "/home/chenying/pythia/pythia/tasks/processors.py", line 407, in _try_download
    self._load_fasttext_model(model_file)
  File "/home/chenying/pythia/pythia/tasks/processors.py", line 466, in _load_fasttext_model
    self.model = load_model(model_file)
  File "/home/chenying/fastText/python/fastText/FastText.py", line 320, in load_model
    return _FastText(path)
  File "/home/chenying/fastText/python/fastText/FastText.py", line 37, in __init__
    self.f.loadModel(model)
ValueError: /home/chenying/pythia/pythia/.vector_cache/wiki.en.bin cannot be opened for loading!

**Comment by CYYYYYYYYYYY** [comment] 2019-05-30 04:29
If any one tell me what's wrong with this

**Comment by apsdehal** [comment] 2019-05-30 07:16
@CYYYYYYYYYYY  Can you pull from master and try again? Thanks.

**Comment by CYYYYYYYYYYY** [comment] 2019-05-30 14:48
I download the file `wiki.en.bin` and put it in `/.vector_cache/` still error but error info changes

INFO: Loading fasttext model now from /home/chenying/pythia/pythia/.vector_cache/wiki.en.bin
2019-05-30T21:59:29 ERROR: DataLoader worker (pid 4347) is killed by signal: Killed. 
Traceback (most recent call last):
  File "tools/run.py", line 94, in <module>
    run()
  File "tools/run.py", line 83, in run
    trainer.train()
  File "/home/chenying/pythia/pythia/trainers/base_trainer.py", line 191, in train
    self.inference()
  File "/home/chenying/pythia/pythia/trainers/base_trainer.py", line 408, in inference
    self._inference_run("test")
  File "/home/chenying/pythia/pythia/trainers/base_trainer.py", line 412, in _inference_run
    self.predict_for_evalai(dataset_type)
  File "/home/chenying/pythia/pythia/trainers/base_trainer.py", line 451, in predict_for_evalai
    for batch in tqdm(dataloader):
  File "/home/chenying/anaconda3/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "/home/chenying/anaconda3/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/utils/data/dataloader.py", line 631, in __next__
    idx, batch = self._get_batch()
  File "/home/chenying/anaconda3/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/utils/data/dataloader.py", line 610, in _get_batch
    return self.data_queue.get()
  File "/home/chenying/anaconda3/lib/python3.6/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/home/chenying/anaconda3/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/chenying/anaconda3/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/chenying/anaconda3/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "/home/chenying/anaconda3/lib/python3.6/site-packages/torch-1.0.1.post2-py3.6-linux-x86_64.egg/torch/utils/data/dataloader.py", line 274, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 4347) is killed by signal: Killed.

**Comment by apsdehal** [comment] 2019-05-30 14:50
This is not related to pythia. This happens when you have insufficient memory (can happen due to other things also, but seeing your error, it seems like memory). Fasttext model itself is 8gb so you will require more than double of that.

**Comment by mandliya** [comment] 2019-06-01 19:08
Aman (@apsdehal), I am seeing this error on machine with 36 GB of RAM. May be it has something to do with config params for number of workers? I am using default params, but may be something needs to be changed?

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 511, in _try_get_batch
    data = self.data_queue.get(timeout=timeout)
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 104, in get
    if timeout < 0 or not self._poll(timeout):
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.5/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/_utils/signal_handling.py", line 63, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1640) is killed by signal: Killed.

**Comment by apsdehal** [comment] 2019-06-01 23:41
@mandliya  You can try adding `training_parameters.num_workers 0` to end of your command. Let me know if works for you.

**Comment by apsdehal** [comment] 2019-06-03 17:25
@CYYYYYYYYYYY Is it working now? Can we close this issue?

**Comment by mandliya** [comment] 2019-06-04 00:45
It worked for me. I played around with num_workers variable and it worked for me with 0 and 2. Not sure why it fails for higher number (I tried 4, 7(default).) I did not dig deeper. I am using Tesla K80. Let me know if you need more details or repro.

**Comment by apsdehal** [comment] 2019-06-04 00:48
The issue is probably memory. Default dataloader in PyTorch creates copy of the dataset for each of the workers. You can google it for more information and https://github.com/pytorch/pytorch/issues/13246. We currently don't plan to support tensor only output from the datasets but it should be easy to remove any strings that are being returned.

**Comment by CYYYYYYYYYYY** [comment] 2019-06-04 01:43
It worked when I try changing `num_workers` with 0; memory error happened when I  tried bigger numbers , such as 2, 4, 7.

Thanks a lot.

**Comment by CYYYYYYYYYYY** [comment] 2019-06-04 01:51
The issue is definitely memory.  CUDA out of memory.

**Comment by apsdehal** [comment] 2019-06-04 01:53
CUDA Memory Error is different. For that, you need to decrease the batch size as you GPU is unable to fit batch size of 512. Try decreasing it to 256 and try again.

**Comment by CYYYYYYYYYYY** [comment] 2019-06-04 02:31
It's ok.

Thanks.

**Closed** 2019-06-04 02:34 UTC
Labels: question
