### ISSUE TITLE
Disproportionate GPU memory usage for LoRRA with nn.DataParallel

### ISSUE THREAD

**Issue by mineshmathew** [facebookresearch/pythia#190] opened 2019-10-31 04:51 UTC
## ❓ Questions and Help
While using nn.DataParallel , the memory usage on main GPU seems to be much larger than the memory it takes on the other GPUs. Below is the case when I run LoRRA with  DataParallel for a batch size of 256.

![lorra_gpu_mem_distribution](https://user-images.githubusercontent.com/13156560/67919839-0193b880-fbc8-11e9-8c49-8629d086ba6f.jpeg)

I tried to see if I can modify the code to for a balanced memory usage and came across this thread here. https://discuss.pytorch.org/t/dataparallel-imbalanced-memory-usage/22551/6

It is suggested that moving loss computation inside forward() of the model would help . But in case of Pythia framework the loss computation is already a part of the forward(). Another reason suggested is the optimizer parameters which are all stored in main GPU. 

If any of you have any ideas on improving it , please help

**Comment by apsdehal** [comment] 2019-10-31 04:57
The issue is in the way DataParallel works. I would suggest you to move to v0.4 branch and use DistributedDataParallel. It has some issues. You can find solutions for those in issues on this repo.

Final v0.4 will be released after CVPR which improves performance and other things but isn't public yet. 

Only other issue that you would face which I can think of is for evalai inference. You can run that in normal DataParallel mode.

**Closed** 2019-10-31 05:23 UTC
